export const Items = [
     {
        name: "REI DOLL",
        img: '/REI DOLL.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI DOLL2",
        img: '/rei1.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI DOLL3",
        img: '/Screenshot 2023-11-28 210429.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },   {
        name: "REI DOLL4",
        img: '/public/Screenshot 2023-11-28 210409.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI DOLL5",
        img: '/Screenshot 2023-11-28 210344.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },{
        name: "REI DOLL6",
   
        img: '/Screenshot 2023-11-28 212808.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI DOLL7",
        img: '/Screenshot 2023-11-28 210511.png',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI figure",
        img: '/8bcf4751242f0f011666b10bb4ae990e.webp',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI figure 2",
        img: '/6d2c044dc66628fb0e42f3a0dcce7226.webp',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI canned bread",
        img: '/public/P1010917.JPG',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI UNIT00(v1)",
        img: '/public/fhqfaww4sae51.jpg',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI UNIT00(v2)",
        img: '/public/61EuCGNMu9L.jpg',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI UNIT00 body pillow",
        img: '/foxtail-img-3682.jpg',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "REI body pillow",
        img: '/S30152b88236747718dbbdd92245930d8p.jpg_640x640Q90.jpg_.webp',
        Shiniji: false,
        REI: true,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "ASUKA DOLL",
        img: '/Screenshot 2023-11-28 215045.png',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA DOLL 2",
        img: '/s-l1600.jpg',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA DOLL 3",
        img: '/IMG_9623__89626.jpg',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA figure",
        img: '/4981932514161_figure-asuka-shikinami-langley-eva2020-ver-evangelion-3-0-1-0-thrice-upon-a-time-altg.jpg',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA figure2",
        img: '/51FC2gDCRHL.jpg',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA UNIT 002 1",
        img: '/513fxap0L6L.webp',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA UNIT 002 2",
        img:'/51gbkO3oTcL.webp',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "ASUKA body pillow",
        img: '/61ORosvpmyL.jpg',
        Shiniji: false,
        REI: false,
        Asuka: true,
        unitCost: 1000,
    },
    {
        name: "Shinji doll",
        img: '/s-l1200.webp',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "Shinji doll2",
        img: '/images.jpg',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "Shinji doll3",
        img: '/images (1).jpg',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "Shinji doll4",
        img: '/55881.jpg',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "Shinji figure",
        img: '/b29eb54ba3ede9156d96c54be640ab07.webp',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
    {
        name: "Shinji figure2",
        img: '/51IlIcru1oL.jpg',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },  {
        name: "Shinji unit 001",
        img: '/Bandai-Eva-Theater-Edition-03-Neon-Genesis-Evangelion-Eva-Evangelion-01-Awakening-Assembly-Model-Kids-Toys-1.jpg',
        Shiniji: true,
        REI: false,
        Asuka: false,
        unitCost: 1000,
    },
 {
    name: "Shinji unit 001 body pillow",
    img: '/il_1080xN.3632519723_8vfs.avif',
    Shiniji: true,
    REI: false,
    Asuka: false,
    unitCost: 1000,
 },
 {
    name: "Shinji body pillow",
    img: '/Screenshot 2023-11-28 222019.png',
    Shiniji: true,
    REI: false,
    Asuka: false,
    unitCost: 1000,
 },
]
